#!/bin/bash

echo "========================================="
echo "AWS CLI Configuration for Thesis Deployment"
echo "========================================="
echo ""
echo "Please run the following command and provide your credentials:"
echo ""
echo "  aws configure --profile thesis-deployment"
echo ""
echo "When prompted, enter:"
echo "  1. AWS Access Key ID: [Your Access Key]"
echo "  2. AWS Secret Access Key: [Your Secret Key]"
echo "  3. Default region name: eu-west-1"
echo "  4. Default output format: json"
echo ""
echo "After configuration, verify with:"
echo "  aws sts get-caller-identity --profile thesis-deployment"
echo ""
echo "========================================="
